### PR TITLE
Automatically join channels when msgs are received / Add custom cookies param / Handle multiple join/parts (rebased)

### PR DESCRIPTION
**Pull request by okurz**
This change is [Reviewable](https://reviewable.io/reviews/mtomwing/pickups/15)

### CODE REVIEW

**Comment by okurz** [comment]
just like #7, only rebased on current master. Tested by me, works good so far.

**Comment by corcoran** [comment]
Is this project dead?  What's going on?  How come it's taking so long to merge these PRs???

**Comment by KwisatzHaderach** [comment]
I have also tried this and it works like a charm.

**Comment by paralin** [comment]
Merge merge merge!

**Comment by okurz** [comment]
@mtomwing would you be so kind to take a look again if you can merge this PR or give feedback which part you are not ok with?

**Comment by okurz** [comment]
https://github.com/bblancha/pickups is probably a better alternative, closing my PR unmerged to cleanup my "open pull request" view

**Pull request closed without merging**
